name: banksampah
description: Aplikasi Pendukung Kegiatan Bank Sampah
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path: ^1.8.3
  sqflite: ^2.3.0
  pdf: ^3.10.0
  open_filex: ^4.4.0
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/trashcan.png
    - assets/icon.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"