name: banksampah
description: Aplikasi Pendukung Kegiatan Bank Sampah
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path: ^1.8.3
  sqflite: ^2.3.0
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/trashcan.png